# Generated by Django 4.2.13 on 2025-01-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='jsonId',
            field=models.CharField(default='SC0', max_length=200),
        ),
    ]
